project:
  type: website
  output-dir: docs

website:
  title: "Portfolio Website"
  site-url: https://rjutha.github.io
  description: "This is Rahim's personal Blog."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Blog
        href: blog.qmd
      - cv.qmd
      - icon: github
        href: https://github.com/rjutha
      - icon: twitter
        href: https://twitter.com/RahimJutha
      - icon: linkedin
        href: https://www.linkedin.com/in/rahim-jutha/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

